(async function(){
'use strict';
const M=JourneyModel,$=s=>document.querySelector(s),phone=$('#phone');
const bytes=Uint8Array.from(atob(window.DETAIL_DATA_GZIP),c=>c.charCodeAt(0));
const DATA=JSON.parse(await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text());
delete window.DETAIL_DATA_GZIP;
const details=new Map(DATA.details.map(s=>[s.key,s]));
const storageKey='deco2500-r5-session';let saved={};try{saved=JSON.parse(sessionStorage.getItem(storageKey)||'{}');}catch{}
let anchor=Number(saved.anchor);if(!anchor||anchor>Date.now())anchor=Date.now();
const state={from:M.LOCATIONS[saved.from]?saved.from:'current',to:saved.to!=='current'&&M.LOCATIONS[saved.to]?saved.to:null,expected:Number(saved.expected)||null,includeLate:saved.includeLate===true&&Boolean(saved.expected),screen:'plan',route:null,stop:null,open:null,error:null,infoReturn:'start'};
let model,currentKey='start',timer,lastMinute=-1;
const now=()=>Math.min(anchor+M.DURATION,Math.max(anchor,Date.now()));
const fmt=ms=>new Date(ms).toLocaleTimeString('en-AU',{hour:'2-digit',minute:'2-digit',hour12:false});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const journey=()=>state.from+'-'+state.to;
const validJourney=()=>Boolean(M.COVERAGE[journey()]);
const laterDay=ms=>new Date(ms).toDateString()!==new Date(now()).toDateString();
const timeLabel=ms=>fmt(ms)+(laterDay(ms)?' tomorrow':'');
function persist(){try{sessionStorage.setItem(storageKey,JSON.stringify({anchor,from:state.from,to:state.to,expected:state.expected,includeLate:state.includeLate}));}catch{}}
function rebuild(){model=M.createModel(DATA.plan,anchor);persist();}
function visibleRoutes(){if(!validJourney())return [];const routes=model.routes(journey(),now());return state.includeLate?routes:M.filterRoutes(routes,state.expected);}
if(state.expected&&!M.validExpected(state.expected,now())){state.expected=null;state.includeLate=false;}rebuild();
function setText(el,value){if(el&&el.textContent!==String(value))el.textContent=value;}
function errorMessage(){if(state.from&&state.to&&state.from===state.to)return ['You cannot select the same departure and destination.','error'];if(state.error==='missing')return ['Please select your departure and destination.',''];if(state.error==='time')return ['Please choose a time after now and within the next 4 hours.',''];if(state.error==='expired')return ['Your selected time has passed. Choose another time, or continue without one.',''];return ['',''];}
function validation(){const [message,type]=errorMessage();return `<p class="validation ${type}" role="status">${message}</p>`;}
function locationField(type,label){const value=state[type],ids=Object.keys(M.LOCATIONS).filter(id=>type==='from'||id!=='current');return `<div class="field" data-field="${type}"><span class="field-label" id="${type}-label">${label}</span><button class="location-trigger" id="${type}-trigger" aria-labelledby="${type}-label ${type}-value" aria-haspopup="listbox" aria-controls="${type}-menu" aria-expanded="${state.open===type}" data-action="open" data-field="${type}"><span id="${type}-value" class="${value?'':'placeholder'}">${value?esc(M.LOCATIONS[value]):type==='from'?'Departure':'Destination'}</span><span class="chevron" aria-hidden="true">⌄</span></button><div class="location-menu" id="${type}-menu" role="listbox" aria-labelledby="${type}-label" ${state.open===type?'':'hidden'}>${ids.map(id=>`<button class="location-option" role="option" aria-selected="${id===value}" data-action="location" data-field="${type}" data-value="${id}">${esc(M.LOCATIONS[id])}</button>`).join('')}</div></div>`;}
function timeOptions(){const range=M.limits(now());let html='<option value="">Any time</option>';for(let t=range.min;t<=range.max;t+=M.MINUTE)html+=`<option value="${t}" ${t===state.expected?'selected':''}>${esc(timeLabel(t))}</option>`;return html;}
function expectedField(){return `<div class="expected-field"><label for="expected-time">Expected arrival time<span class="optional">(optional)</span></label><select id="expected-time" aria-label="Expected arrival time (optional)">${timeOptions()}</select></div>`;}
const symbols={you:'<path d="M8 1L15 14L8 11L1 14Z" fill="#ee3b39"/>',stops:'<circle cx="8" cy="8" r="5" fill="#4034e6"/>',route:'<path d="M0 8H15M10 3L15 8L10 13" fill="none" stroke="#f51bb6" stroke-width="2.5"/>',destination:'<path d="M2 2L14 14M14 2L2 14M8 0V16M0 8H16" fill="none" stroke="#ed3939" stroke-width="2"/>'};
function legend(full=true){return `<div class="legend">${[['you','You'],['stops','Stops'],...(full?[['route','Bus route'],['destination','Destination']]:[])].map(([key,title])=>`<span class="${key}"><svg viewBox="0 0 16 16" aria-hidden="true">${symbols[key]}</svg>${title}</span>`).join('')}</div>`;}
const routePoints={'411':[[49,91],[97,78],[142,63],[223,40],[223,104],[305,90],[300,215]],'412':[[58,115],[96,115],[141,115],[142,173],[223,173],[231,223],[282,223]],'444':[[40,132],[31,167],[24,211],[79,211],[79,257],[203,257],[278,237]]};
function basemap(){const local=!state.to||(state.from==='current'&&state.to==='uq');return `<rect width="350" height="278" fill="#deedf5"/><path d="M0 0H350V58L320 92L263 74L202 49L141 62L62 34L0 43Z" fill="#cef0be"/><path d="M0 44L48 54L39 161L0 153Z M155 69L188 62L196 100L180 129L198 173L155 187L135 142Z M244 134L350 113V254L270 250L222 218Z M0 251L100 228L186 257L235 278H0Z" fill="#d2efc6"/><path d="M267 0L303 0L350 47V70L314 48Z M0 278L350 250V278Z" fill="#98d9ec"/><path d="M279 155Q295 155 285 176T291 204Q282 228 262 219T266 194Q283 181 272 169Z" fill="#a0dbec"/><g fill="#e8f0f4" stroke="#d2e0e7" stroke-width="1"><path d="M64 61L131 72L123 104L60 99Z M66 124L123 129L120 151L61 142Z M176 202L217 197L228 227L185 236Z M215 84L251 76L264 106L221 114Z M105 207L148 174L160 189L117 224Z"/></g><g fill="none" stroke="#cad9df" stroke-width="8" stroke-linejoin="round"><path d="M-5 34L139 59L155 60L250 36L359 111 M66 -10L51 50L40 170L21 274 M95 -10L73 52L59 111L45 177 M174 -10L154 61L143 114L145 169L104 209L70 281 M0 170L88 187L138 171L219 177L230 235L353 220 M0 256L108 210 M45 111L139 117 M212 58L225 104L310 88L300 234 M69 250L217 252L274 232"/></g><g fill="none" stroke="#f7faf9" stroke-width="5" stroke-linejoin="round"><path d="M-5 34L139 59L155 60L250 36L359 111 M66 -10L51 50L40 170L21 274 M95 -10L73 52L59 111L45 177 M174 -10L154 61L143 114L145 169L104 209L70 281 M0 170L88 187L138 171L219 177L230 235L353 220 M0 256L108 210 M45 111L139 117 M212 58L225 104L310 88L300 234 M69 250L217 252L274 232"/></g><g class="road-label"><text x="77" y="65" transform="rotate(10 77 65)">${local?'Glasshouse Rd':'Local bus corridor'}</text><text x="66" y="135">${local?'Hood St':'High St'}</text><text x="29" y="121" transform="rotate(-81 29 121)">${local?'Walcott St':'Station Rd'}</text><text x="73" y="231" transform="rotate(-37 73 231)">${local?'Hawken Dr':'Connecting road'}</text></g><g class="area-label"><text x="208" y="128">${local?'UQ campus':'Brisbane'}</text><text x="218" y="143">${local?'St Lucia':'River'}</text><text x="89" y="27">${local?'Playing fields':'Neighbourhood park'}</text><text x="32" y="270" style="font-size:9px">Brisbane River</text></g>`;}
function drawMap(kind,route){const routes=kind==='plan'?[]:kind==='nearby'?[route]:visibleRoutes().map(r=>r.route),you=kind==='plan'?[173,137]:[36,64],end=[300,239];let overlay='';
 function circle([x,y],r=4.3){return `<circle cx="${x}" cy="${y}" r="${r}" fill="#4236e8" stroke="white" stroke-width=".7"/>`;}
 if(kind==='plan'){overlay=[[47,99],[125,72],[235,51],[282,99],[277,178],[187,205],[91,222]].map(p=>circle(p,4.7)).join('');}
 for(const r of routes){const pts=routePoints[r];overlay+=`<polyline class="bus-line" data-route="${r}" points="${pts.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#f51bb6" stroke-width="5" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#route-arrow)"/>`;
  if(kind==='nearby'){overlay+=pts.slice(0,3).map(([x,y],i)=>`<path d="M36 64Q${x-13} ${Math.max(32,y-25)} ${x} ${y}" fill="none" stroke="#655bdf" stroke-width="1.5" stroke-dasharray="4 4"/>${circle([x,y],5)}<text class="stop-label" x="${x}" y="${y+19}" text-anchor="middle">Stop ${i+1}</text>`).join('');}else{overlay+=pts.slice(0,-1).map(p=>circle(p)).join('')+`<text class="route-label" x="${pts[1][0]+3}" y="${pts[1][1]-9}">${r}</text>`;}}
 overlay+=`<path d="M${you[0]} ${you[1]-10}l9 19-9-4-9 4Z" fill="#ed3c36" stroke="white" stroke-width="1.5"/><text x="${you[0]+13}" y="${you[1]+3}" fill="#c42f2f" font-size="10" font-weight="700" paint-order="stroke" stroke="white" stroke-width="2">You</text>`;
 if(kind!=='plan'&&validJourney())overlay+=`<path d="M${end[0]-6} ${end[1]-6}l12 12m0-12-12 12m6-15v18m-9-9h18" fill="none" stroke="#f03835" stroke-width="2.8"/><text x="342" y="264" text-anchor="end" fill="#b82929" font-size="10" font-weight="700" paint-order="stroke" stroke="white" stroke-width="2">Destination</text>`;
 const title=kind==='plan'?'Map showing your position and nearby bus stops':`${routes.length} ${kind==='nearby'?'bus route with three labelled stops':'bus routes'} from ${M.LOCATIONS[state.from]||'your departure'} to ${M.LOCATIONS[state.to]||'your destination'}`;
 return `<div class="map"><svg viewBox="0 0 350 278" role="img" aria-label="${esc(title)}"><defs><marker id="route-arrow" markerWidth="6" markerHeight="6" refX="4" refY="3" orient="auto"><path d="M1 1L4 3L1 5" fill="none" stroke="#f51bb6" stroke-width="1.2"/></marker></defs>${basemap()}${overlay}</svg></div>`;
}
function topbar(back){return `<div class="topbar">${back?`<button class="back" data-action="back">‹ Back</button>`:''}<span class="clock" data-name="Live clock"></span></div>`;}
function etaHeading(){return '<button class="eta-heading" data-action="eta-info" aria-label="About estimated arrival time"><span>Estimated arrival time</span><span class="info-icon" aria-hidden="true">i</span></button>';}
function arrivalExplanation(){return `${topbar(true)}<h1 tabindex="-1">Estimated arrival time</h1><div class="arrival-explanation"><p>This is the time you are expected to reach your final destination, starting from your current location, including transit time to the platform and to the destination after getting off.</p></div>`;}
// The selected stop uses the same coordinates and walking connection as its comparison map.
function drawStopMap(route,number){
 const points=routePoints[route],you=[36,64],stop=points[number-1],ratio=350/240;
 const width=Math.max(180,Math.abs(stop[0]-you[0])+70,(Math.abs(stop[1]-you[1])+62)*ratio),height=width/ratio;
 const left=Math.max(0,Math.min(350-width,(you[0]+stop[0])/2-width/2)),top=Math.max(0,Math.min(278-height,(you[1]+stop[1])/2-height/2));
 const zoom=350/width,unit=1/zoom,[x,y]=stop;
 // Labels and markers stay readable while the underlying neighbourhood is magnified.
 const labelY=y+21*unit,labelX=x+8*unit;
 return `<div class="map stop-map"><svg viewBox="${left} ${top} ${width} ${height}" role="img" aria-label="Walking route from ${esc(M.LOCATIONS[state.from])} to Stop ${number} for Bus ${route}" data-stop="${number}" data-route="${route}" data-zoom="${zoom}">
 ${basemap()}
 <polyline class="bus-line" data-route="${route}" points="${points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#f51bb6" stroke-width="5.5" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round"/>
 <path class="walking-path" d="M36 64Q${x-13} ${Math.max(32,y-25)} ${x} ${y}" fill="none" stroke="white" stroke-width="4.5" vector-effect="non-scaling-stroke"/>
 <path class="walking-path" d="M36 64Q${x-13} ${Math.max(32,y-25)} ${x} ${y}" fill="none" stroke="#4034e6" stroke-width="2.5" stroke-dasharray="4 4" vector-effect="non-scaling-stroke"/>
 <circle class="selected-stop" cx="${x}" cy="${y}" r="${6.5*unit}" fill="#4034e6" stroke="white" stroke-width="1.5" vector-effect="non-scaling-stroke"/>
 <text class="selected-stop-label" x="${labelX}" y="${labelY}" fill="#302ccc" font-size="${13*unit}" font-weight="700" paint-order="stroke" stroke="white" stroke-width="${3*unit}">Stop ${number}</text>
 <g class="you-marker" transform="translate(36 64) scale(${unit})"><path d="M0 -11L10 10L0 5L-10 10Z" fill="#ed3c36" stroke="white" stroke-width="1.5"/><text x="15" y="3" fill="#bd302c" font-size="12" font-weight="700" paint-order="stroke" stroke="white" stroke-width="3">You</text></g>
 </svg></div>`;
}
function detailCrowding(snapshot){
 const group=snapshot.children.find(n=>n.name==='Crowding breakdown');
 const levels=[['Stop crowding','Platform crowding level'],['Bus crowding','Crowding levels on the arriving bus']].map(([name,label])=>{
  const row=group.children.find(n=>n.name===name);
  return {label,value:Number(row.children.find(n=>n.name==='Value').text.split('/')[0].trim())};
 });
 // Both 1–10 factors have equal weight; display the nearest whole level.
 return {levels,combined:Math.round((levels[0].value+levels[1].value)/2)};
}
function stopDetail(snapshot){
 const s=model.stop(journey(),state.route,state.stop,now()),crowding=detailCrowding(snapshot);
 const mapLegend=`<div class="legend">${[['you','You'],['stops','Stops'],['route','Bus route']].map(([key,title])=>`<span class="${key}"><svg viewBox="0 0 16 16" aria-hidden="true">${symbols[key]}</svg>${title}</span>`).join('')}</div>`;
 return `<header class="detail-header"><button class="back" data-action="back">‹ Back</button><span class="clock" data-name="Live clock"></span><div class="detail-eta">${etaHeading()}${etaMarkup()}</div></header>
 <h1 tabindex="-1">Bus ${state.route} · Stop ${state.stop}</h1>
 ${drawStopMap(state.route,state.stop)}${mapLegend}
 <div class="detail-body">
 <section class="boarding-card" aria-label="Chance to catch the next bus"><strong data-name="Probability"></strong><span>chance to catch<br>the next bus</span></section>
 <section class="walking-card" aria-label="Walk to this stop"><h2 data-name="Walking distance">Walking distance: ${s.metres} m</h2><p data-name="Estimated walking time">Estimated walking time: ${s.walkMinutes} min</p><p data-name="Walking arrival"></p></section>
 <section class="crowding-section" aria-labelledby="crowding-title"><h2 id="crowding-title">Combined crowding level: ${crowding.combined}/10</h2><dl>${crowding.levels.map(c=>`<div><dt>${esc(c.label)}</dt><dd>${c.value} / 10</dd></div>`).join('')}</dl><p class="scale-note">1 = quiet · 10 = very crowded</p></section>
 <section class="arrivals-section" aria-labelledby="arrivals-title"><h2 id="arrivals-title">Next arrivals at this stop</h2><p class="arrival-times" data-name="Arrival times"></p><p class="next-bus" data-name="Arrival countdown"></p></section>
 <button class="primary" data-action="compare-stops">Compare other stops</button>
 </div>`;
}

function render(focusHeading=false){state.open=null;phone.className=state.screen==='detail'?'detail':'';phone.removeAttribute('style');phone.dataset.key=currentKey;lastMinute=-1;
 if(state.screen==='detail'){const key=`${journey()}-detail-${state.route}-${state.stop}-0`,snapshot=details.get(key);if(!snapshot){go('start');return;}phone.innerHTML=`<section class="screen stop-detail">${stopDetail(snapshot)}</section>`;}
 else {let body='';if(state.screen==='plan'){body=`${topbar(false)}<h1 tabindex="-1">Plan your journey</h1>${drawMap('plan')}${legend(false)}${locationField('from','Start your journey from')}${locationField('to','To')}${expectedField()}${validation()}<button class="primary" data-action="find">Find bus routes</button>`;}
 else if(state.screen==='routes'){body=`${topbar(true)}<h1 tabindex="-1">Choose a bus route</h1><div class="journey-fields">${locationField('from','From')}${locationField('to','To')}</div>${expectedField()}${validation()}${drawMap('routes')}${legend()}<div class="comparison-heading"><h2><span class="route-count">${visibleRoutes().length}</span><span class="route-count-label">available routes</span></h2>${etaHeading()}</div><div id="late-routes-notice" class="late-routes-notice" hidden></div><div class="comparison-list" id="route-list"></div>`;}
 else if(state.screen==='eta-info'){body=arrivalExplanation();}
 else {body=`${topbar(true)}<h1 tabindex="-1">Bus ${state.route} · nearby stops<small>Within 1 km</small></h1>${drawMap('nearby',state.route)}${legend()}<div class="comparison-heading"><h2>Chance to catch the next bus</h2>${etaHeading()}</div><div class="comparison-list" id="stop-list"></div>`;}
 phone.innerHTML=`<section class="screen ${state.screen}">${body}</section>`;}
 update();if(focusHeading){phone.querySelector('h1')?.focus({preventScroll:true});window.scrollTo(0,0);}persist();}
function etaMarkup(){return '<span class="eta"><time></time><small></small></span>';}
function updateEta(row,ms){row.dataset.etaMs=ms;const time=row.querySelector('.eta time');time.dateTime=new Date(ms).toISOString();setText(time,fmt(ms));setText(row.querySelector('.eta small'),laterDay(ms)?'tomorrow':'');}
function reorder(parent,rows){rows.forEach((node,i)=>{if(parent.children[i]!==node)parent.insertBefore(node,parent.children[i]||null);});}
function routeList(){const parent=$('#route-list');if(!parent)return;const all=validJourney()?model.routes(journey(),now()):[],matched=M.filterRoutes(all,state.expected),lateCount=all.length-matched.length,values=state.includeLate?all:matched;
 setText($('.route-count'),values.length);setText($('.route-count-label'),values.length===1?'available route':'available routes');
 const map=$('.routes .map'),mapRoutes=[...map.querySelectorAll('.bus-line')].map(n=>n.dataset.route).sort().join(','),nextRoutes=values.map(r=>r.route).sort().join(',');if(mapRoutes!==nextRoutes)map.outerHTML=drawMap('routes');
 const notice=$('#late-routes-notice');notice.hidden=!(lateCount&&values.length);if(!notice.hidden){const stamp=`${lateCount}:${state.includeLate}`;if(notice.dataset.stamp!==stamp){const subject=`${lateCount} ${lateCount===1?'route arrives':'routes arrive'}`;notice.innerHTML=`<p role="status">${subject} more than ${M.LATE_TOLERANCE_MINUTES} minutes after your expected arrival time. ${state.includeLate?'These routes are now shown.':'Would you like to see '+(lateCount===1?'it':'them')+'?'}</p><button class="secondary" data-action="${state.includeLate?'hide-late':'show-late'}">${state.includeLate?'Hide later routes':'Show later routes'}</button>`;notice.dataset.stamp=stamp;}}
 if(!validJourney()){if(!parent.querySelector('.empty'))parent.innerHTML='<p class="empty">Choose two different locations to see routes.</p>';return;}
 if(!values.length){const stamp=String(state.expected);if(parent.dataset.emptyTarget!==stamp){parent.innerHTML=`<div class="no-routes" role="status"><h3>No suitable buses found</h3><p>All routes arrive more than ${M.LATE_TOLERANCE_MINUTES} minutes after your expected arrival time of <strong>${esc(timeLabel(state.expected))}</strong>.</p><p>Would you like to see these later routes anyway?</p><button class="primary" data-action="show-late">Show later routes</button><button class="secondary" data-action="choose-time">Choose another time</button></div>`;parent.dataset.emptyTarget=stamp;}return;}
 delete parent.dataset.emptyTarget;parent.querySelectorAll('.empty,.no-routes').forEach(el=>el.remove());const ids=new Set(values.map(r=>r.route));parent.querySelectorAll('[data-route]').forEach(el=>{if(!ids.has(el.dataset.route))el.remove();});
 const rows=[];for(const r of values){let row=parent.querySelector(`[data-route="${r.route}"]`);if(!row){row=document.createElement('button');row.className='comparison-row';row.dataset.action='route';row.dataset.route=r.route;row.innerHTML=`<span class="card"><span class="route-title">Bus ${r.route}</span><span class="distance"><strong>${r.metres}</strong><span class="unit">m</span><span class="caption">to the nearest stop</span></span><span class="row-arrow" aria-hidden="true">›</span></span>${etaMarkup()}`;const note=document.createElement('span');note.className='late-arrival';row.querySelector('.eta').append(note);parent.append(row);}updateEta(row,r.etaMs);const late=state.expected!==null&&r.etaMs>state.expected+M.LATE_TOLERANCE_MINUTES*M.MINUTE,lateMinutes=state.expected?Math.ceil((r.etaMs-state.expected)/M.MINUTE):0;row.dataset.late=String(late);setText(row.querySelector('.late-arrival'),late?`${lateMinutes} min late`:'');row.setAttribute('aria-label',`Bus ${r.route}, ${r.metres} metres to the nearest stop, estimated arrival at destination ${timeLabel(r.etaMs)}${late?', '+lateMinutes+' minutes after your expected time':''}`);rows.push(row);}reorder(parent,rows);}
function stopList(){const parent=$('#stop-list');if(!parent)return;const values=model.stops(journey(),state.route,now()),rows=[];for(const s of values){let row=parent.querySelector(`[data-stop="${s.stop}"]`);if(!row){row=document.createElement('button');row.className='comparison-row';row.dataset.action='stop';row.dataset.stop=s.stop;row.innerHTML=`<span class="card stop-card"><span class="stop-copy"><h3>Stop ${s.stop}</h3><span class="walk">Walk ${s.walkMinutes} min · ${s.metres} m</span><br><span class="next-bus"></span></span><span class="chance"></span><span class="row-arrow" aria-hidden="true">›</span></span>${etaMarkup()}`;parent.append(row);}setText(row.querySelector('.next-bus'),`Next bus ${fmt(s.arrivalMs)} · ${s.remainingLabel}`);setText(row.querySelector('.chance'),s.percent+'%');updateEta(row,s.etaMs);row.dataset.arrivalMs=s.arrivalMs;row.dataset.chance=s.percent;row.setAttribute('aria-label',`Stop ${s.stop}, walk ${s.walkMinutes} minutes, ${s.percent}% chance to catch the next bus, next bus ${fmt(s.arrivalMs)}, estimated destination arrival ${timeLabel(s.etaMs)}`);rows.push(row);}reorder(parent,rows);}
function update(){const n=now(),elapsed=Math.floor((n-anchor)/1000),ended=elapsed>=180;document.querySelectorAll('[data-name="Live clock"]').forEach(el=>setText(el,'Current time: '+new Date(n).toLocaleTimeString('en-AU',{hour12:false})));setText($('#demo-status'),ended?'Three-minute demo complete · Time paused':`Three-minute demo · ${Math.floor(elapsed/60)}:${String(elapsed%60).padStart(2,'0')} / 3:00`);$('#restart').hidden=!ended;
 if(state.expected&&!M.validExpected(state.expected,n)){state.expected=null;state.includeLate=false;state.error='expired';persist();const message=$('.validation');if(message){setText(message,errorMessage()[0]);message.classList.remove('error');}}
 const minute=Math.floor(n/M.MINUTE);if(minute!==lastMinute){lastMinute=minute;const select=$('#expected-time');if(select)select.innerHTML=timeOptions();}
 if(state.screen==='routes')routeList();else if(state.screen==='nearby')stopList();else if(state.screen==='detail'){const s=model.stop(journey(),state.route,state.stop,n);setText($('[data-name="Probability"]'),s.percent+'%');setText($('[data-name="Arrival times"]'),s.arrivalTimestamps.map(fmt).join('   ·   '));setText($('[data-name="Arrival countdown"]'),'Next bus in '+s.remainingLabel);setText($('[data-name="Walking arrival"]'),'Reach stop around '+fmt(s.walkingArrivalMs));phone.dataset.arrivalMs=s.arrivalMs;updateEta($('.detail-eta'),s.etaMs);}
 if(ended&&timer){clearInterval(timer);timer=null;}}
function go(key){if(location.hash.slice(1)===key)navigate();else location.hash=key;}
function navigate(){const previousJourney=journey();let key;try{key=decodeURIComponent(location.hash.slice(1));}catch{key='start';}const info=key.startsWith('arrival-info/');if(info)key=key.slice('arrival-info/'.length);const match=key.match(/^(current|uq|towoong|roma)-(uq|towoong|roma)-(compare|detail)-(411|412|444)(?:-([123]))?-[01]$/),routeMatch=key.match(/^routes-(current|uq|towoong|roma)-(uq|towoong|roma)$/);
 if(match&&M.COVERAGE[match[1]+'-'+match[2]]){state.from=match[1];state.to=match[2];state.route=match[4];state.screen=match[3]==='compare'?'nearby':'detail';state.stop=Number(match[5])||1;}
 else if(routeMatch&&M.COVERAGE[routeMatch[1]+'-'+routeMatch[2]]){state.from=routeMatch[1];state.to=routeMatch[2];state.screen='routes';}
 else {state.screen='plan';key='start';}if(previousJourney!==journey())state.includeLate=false;state.error=null;if(info){state.infoReturn=key;state.screen='eta-info';key='arrival-info/'+key;}currentKey=key;render(true);}
function closeMenus(){state.open=null;phone.querySelectorAll('.location-menu').forEach(el=>el.hidden=true);phone.querySelectorAll('.location-trigger').forEach(el=>el.setAttribute('aria-expanded','false'));}
phone.addEventListener('click',event=>{const action=event.target.closest('[data-action]');if(!action){const target=event.target.closest('[data-target]');if(target)go(DATA.targets[target.dataset.target]);return;}const a=action.dataset.action;
 if(a==='open'){const field=action.dataset.field,was=state.open===field;closeMenus();if(!was){state.open=field;$('#'+field+'-menu').hidden=false;action.setAttribute('aria-expanded','true');}return;}
 if(a==='location'){const field=action.dataset.field;if(state[field]!==action.dataset.value)state.includeLate=false;state[field]=action.dataset.value;state.error=null;persist();if(state.screen==='routes'&&validJourney()){currentKey='routes-'+journey();history.replaceState(null,'','#'+currentKey);}render();$('#'+field+'-trigger')?.focus({preventScroll:true});return;}
 if(a==='find'){if(!state.from||!state.to){state.error='missing';render();return;}if(state.from===state.to){render();return;}go('routes-'+journey());}
 if(a==='back'){go(state.screen==='eta-info'?state.infoReturn:state.screen==='detail'?`${journey()}-compare-${state.route}-0`:state.screen==='routes'?'start':'routes-'+journey());}
 if(a==='compare-stops')go(`${journey()}-compare-${state.route}-0`);
 if(a==='eta-info')go('arrival-info/'+currentKey);
 if(a==='show-late'||a==='hide-late'){state.includeLate=a==='show-late';persist();update();const toggle=$('#late-routes-notice button')||$('.no-routes [data-action="show-late"]');toggle?.focus({preventScroll:true});}
 if(a==='choose-time')$('#expected-time')?.focus();
 if(a==='route')go(`${journey()}-compare-${action.dataset.route}-0`);
 if(a==='stop')go(`${journey()}-detail-${state.route}-${action.dataset.stop}-0`);
});
phone.addEventListener('change',event=>{if(event.target.id!=='expected-time')return;const value=event.target.value?Number(event.target.value):null;if(value&&!M.validExpected(value,now())){state.error='time';render();return;}state.expected=value;state.includeLate=false;state.error=null;persist();update();setText($('.validation'),errorMessage()[0]);});
phone.addEventListener('focusin',event=>{if(event.target.id==='expected-time')closeMenus();});
document.addEventListener('click',event=>{if(!event.target.closest('.field'))closeMenus();});
phone.addEventListener('keydown',event=>{if(event.key==='Escape'&&state.open){const field=state.open;closeMenus();$('#'+field+'-trigger').focus();event.preventDefault();return;}const trigger=event.target.closest('.location-trigger');if(trigger&&['ArrowDown','ArrowUp'].includes(event.key)){event.preventDefault();if(state.open!==trigger.dataset.field)trigger.click();$('#'+trigger.dataset.field+'-menu').querySelector('button').focus();return;}const option=event.target.closest('.location-option');if(option&&['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();const options=[...option.parentNode.children],index=options.indexOf(option),next=event.key==='Home'?0:event.key==='End'?options.length-1:(index+(event.key==='ArrowDown'?1:-1)+options.length)%options.length;options[next].focus();return;}if(event.key==='Enter'||event.key===' '){const target=event.target.closest('.node[data-target]');if(target){event.preventDefault();target.click();}}});
function startTimer(){if(timer)clearInterval(timer);timer=setInterval(update,1000);update();}
$('#restart').addEventListener('click',()=>{anchor=Date.now();state.includeLate=false;if(state.expected&&!M.validExpected(state.expected,anchor))state.expected=null;rebuild();render();startTimer();});
addEventListener('hashchange',navigate);addEventListener('pageshow',update);addEventListener('focus',update);document.addEventListener('visibilitychange',()=>{if(!document.hidden)update();});
window.PROTOTYPE={version:8,data:DATA,get state(){return {...state};},get anchor(){return anchor;},get now(){return now();},get model(){return model;},get current(){return {key:currentKey};},updateClock:update,navigate:go};navigate();startTimer();
})().catch(error=>{console.error(error);document.querySelector('#phone').innerHTML='<p class="loading">The prototype could not open. Please reload the page.</p>';});
